### ISSUE TITLE
running the docker image as non-root

### ISSUE THREAD

**Issue by mhaberler** [cdsteinkuehler/QuartusBuildVMs#3]
I'm trying to run the docker image as a non-root user - jenkins runs docker images as user jenkins by default which is a vanilla user, to make it easier to parameterize

for that, a minor touchup is needed : `chmod 755 /root` so a non-root user can get at the files under /root

but the thing I cannot get baked is this: if running as non-root everything works until almost done, then this:

```
Info: Command: quartus_stp DE0_NANO
Inconsistency detected by ld.so: dl-close.c: 762: _dl_close: Assertion `map->l_init_called' failed!
Error (262009): Can't open SignalTap II Logic Analyzer. Verify that the license file exists and is stored in the correct location. If you are using the Quartus Prime Lite Edition software, you must turn on the TalkBack feature to use the SignalTap II Logic Analyzer.
Error: Quartus Prime SignalTap II was unsuccessful. 1 error, 0 warnings
    Error: Peak virtual memory: 1035 megabytes
    Error: Processing ended: Fri May 20 14:36:32 2016
    Error: Elapsed time: 00:00:03
    Error: Total CPU time (on all processors): 00:00:04
```

it must be this stupid talkback feature. Any ideas how to make that work from a non-root user? some file from the home dir missing or somesuch?

**Comment by cdsteinkuehler** [comment]
It's likely one of two things:

Either the talkback 'magic' isn't installed properly for the user
you're running as (in which case this might help:
https://github.com/cdsteinkuehler/QuartusBuildVMs/blob/master/Jessie-Quartus-15.1.2/Dockerfile#L27
)

...or the signal-tap program isn't working properly.  I had to change
the makefile to get around a similar problem, but I don't recall if it
was the signal-tap program or something else that was failing:

https://github.com/cdsteinkuehler/QuartusBuildVMs/blob/master/Jessie-Quartus-15.1.2/Dockerfile#L27

Also, I'd recommend simply adding a user to the Docker install and
installing all the Quartus tools non-root.  I can do this if you like.

## 

Charles Steinkuehler
charles@steinkuehler.net

**Comment by mhaberler** [comment]
I would really appreciate this - I spent hours on trying to rebuild that image for non-root to no avail

to check if things work:

whatever the image default user.. jenkins starts the docker image like so:

`docker run -u 1030:1032 ....`

(1030/1032 happens to be jenkins/jenkins on the current host - the image should not depend on any particular value)

if the quartus build still works with this, we're in business and can drop this script from /scripts which eases parameterization!

**Comment by mhaberler** [comment]
the key to the talkback issue was: Quartus relies on `$HOME` to find the `.altera.quartus` subdirectory which contains talkback-related files

now running a docker instance does not automatically create a login user so HOME is unset by default, so that user does not find those files (same goes for PATH from .profile and the Altera-specific environment variables)

explicitly injecting HOME PATH QSYS_ROOTDIR ALTERAOCLSDKROOT environment variables into the container at startup fixed it

**Comment by mhaberler** [comment]
resolved
